export const prizes = [
    {code: 0, value: 0, time: "永久", name: "至尊·盘龙（永久）", type: "s", position: [0, 0]},
    {code: 1, value: 0, time: "永久", name: "至尊·麦凯伦（永久）", type: "s", position: [0, 2]},
    {code: 2, value: 0, time: "永久", name: "启灵守护神（永久）", type: "t1", position: [1, 0]},
    {code: 3, value: 0, time: "永久", name: "侍武之魂（永久）", type: "t1", position: [1, 2]},
    {code: 5, value: 0, time: "永久", name: "缤纷神驹（永久）", type: "a", position: [2, 0]},
    {code: 6, value: 0, time: "永久", name: "白玉神驹（永久）", type: "a", position: [2, 2]},
    {code: 7, value: 0, time: "永久", name: "睡梦阿狸（永久）", type: "b", position: [3, 0]},
    {code: 8, value: 0, time: "永久", name: "萌菜出击（永久）", type: "b", position: [3, 1]},
    {code: 9, value: 0, time: "永久", name: "逐浪独角兽（永久）", type: "b", position: [3, 2]},
    {code: 10, value: 0, time: "30天", name: "至尊·盘龙（30天）", type: "s", position: [0, 0]},
    {code: 11, value: 0, time: "1天", name: "至尊·盘龙（1天）", type: "s", position: [0, 1]},
    {code: 12, value: 0, time: "30天", name: "至尊·麦凯伦（30天）", type: "s", position: [0, 2]},
    {code: 13, value: 0, time: "1天", name: "至尊·麦凯伦（1天）", type: "s", position: [0, 3]},
    {code: 14, value: 0, time: "30天", name: "启灵守护神（30天）", type: "t1", position: [1, 0]},
    {code: 15, value: 0, time: "1天", name: "启灵守护神（1天）", type: "t1", position: [1, 1]},
    {code: 16, value: 0, time: "30天", name: "侍武之魂（30天）", type: "t1", position: [1, 2]},
    {code: 17, value: 0, time: "1天", name: "侍武之魂（1天）", type: "t1", position: [1, 3]},
    {code: 18, value: 0, time: "30天", name: "缤纷神驹（30天）", type: "a", position: [2, 0]},
    {code: 19, value: 0, time: "1天", name: "缤纷神驹（1天）", type: "a", position: [2, 1]},
    {code: 20, value: 0, time: "30天", name: "白玉神驹（30天）", type: "a", position: [2, 2]},
    {code: 21, value: 0, time: "1天", name: "白玉神驹（1天）", type: "a", position: [2, 3]},
    {code: 22, value: 0, time: "10天", name: "睡梦阿狸（10天）", type: "b", position: [3, 0]},
    {code: 23, value: 0, time: "10天", name: "萌菜出击（10天）", type: "b", position: [3, 1]},
    {code: 24, value: 0, time: "10天", name: "逐浪独角兽（10天）", type: "b", position: [3, 2]},
    {code: 25, value: 0, time: "10天", name: "消除联萌（10天）", type: "b", position: [3, 3]},
    {code: 26, value: 0, time: "永久", name: '终极烈焰新星（永久）', type: "s"},
    {code: 27, value: 0, time: "永久", name: '至尊青龙（永久）', type: "t1"},
    {code: 28, value: 0, time: "永久", name: '恭贺新春座椅（永久）', type: "s"},
    {code: 29, value: 0, time: "永久", name: '傲世青龙（永久）', type: "s"},
    {code: 30, value: 0, time: "永久", name: '浮华星海背饰（永久）', type: "s"},
    {code: 31, value: 0, time: "永久", name: '天光云影发饰（永久）', type: "s"},
    {code: 32, value: 0, time: "永久", name: '天光云影服饰（永久）', type: "s"},
    {code: 33, value: 0, time: "永久", name: '暮色蔷薇手杖（永久）', type: "s"}
]
export const prizesCodeSortByValue = [22, 23, 24, 25, 19, 21, 15, 17, 11, 13, 18, 20, 14, 16, 10, 12]